[
    {
        "File": "fr_errors.po",
        "BBFiles": [
            "conf/distro/include/default-distrovars.inc",
            "conf/distro/include/default-providers.inc",
            "conf/distro/include/default-versions.inc",
            "conf/distro/include/init-manager-none.inc",
            "conf/distro/include/maintainers.inc",
            "conf/distro/include/no-static-libs.inc",
            "conf/distro/include/poky-world-exclude.inc",
            "conf/distro/include/security_flags.inc",
            "conf/distro/include/tclibc-glibc.inc",
            "conf/distro/include/tcmode-default.inc",
            "conf/distro/include/uninative-flags.inc",
            "conf/distro/include/yocto-uninative.inc",
            "conf/machine/include/qemu.inc",
            "conf/machine/include/qemuboot-x86.inc",
            "conf/machine/include/tune-core2.inc",
            "conf/machine/include/tune-i586.inc",
            "conf/machine/include/tune-i686.inc",
            "conf/machine/include/x86/arch-x86.inc",
            "dynamic-distro/scatest/code-from-elsewhere/bad-po.bb"
        ],
        "BuildPath": "/mnt/data/yocto/build-sca-master/tmp/work/core2-64-scatest-linux/bad-po/1.0-r0/git/tests",
        "Line": "42",
        "Column": "1",
        "Severity": "warning",
        "Message": "number of lines: 2 in string, 1 in translation",
        "ID": "lines",
        "PackageName": "bad-po",
        "Tool": "msgcheck",
        "Scope": "style"
    },
    {
        "File": "fr_errors.po",
        "BBFiles": [
            "conf/distro/include/default-distrovars.inc",
            "conf/distro/include/default-providers.inc",
            "conf/distro/include/default-versions.inc",
            "conf/distro/include/init-manager-none.inc",
            "conf/distro/include/maintainers.inc",
            "conf/distro/include/no-static-libs.inc",
            "conf/distro/include/poky-world-exclude.inc",
            "conf/distro/include/security_flags.inc",
            "conf/distro/include/tclibc-glibc.inc",
            "conf/distro/include/tcmode-default.inc",
            "conf/distro/include/uninative-flags.inc",
            "conf/distro/include/yocto-uninative.inc",
            "conf/machine/include/qemu.inc",
            "conf/machine/include/qemuboot-x86.inc",
            "conf/machine/include/tune-core2.inc",
            "conf/machine/include/tune-i586.inc",
            "conf/machine/include/tune-i686.inc",
            "conf/machine/include/x86/arch-x86.inc",
            "dynamic-distro/scatest/code-from-elsewhere/bad-po.bb"
        ],
        "BuildPath": "/mnt/data/yocto/build-sca-master/tmp/work/core2-64-scatest-linux/bad-po/1.0-r0/git/tests",
        "Line": "45",
        "Column": "1",
        "Severity": "warning",
        "Message": "number of lines: 2 in string, 3 in translation",
        "ID": "lines",
        "PackageName": "bad-po",
        "Tool": "msgcheck",
        "Scope": "style"
    },
    {
        "File": "fr_errors.po",
        "BBFiles": [
            "conf/distro/include/default-distrovars.inc",
            "conf/distro/include/default-providers.inc",
            "conf/distro/include/default-versions.inc",
            "conf/distro/include/init-manager-none.inc",
            "conf/distro/include/maintainers.inc",
            "conf/distro/include/no-static-libs.inc",
            "conf/distro/include/poky-world-exclude.inc",
            "conf/distro/include/security_flags.inc",
            "conf/distro/include/tclibc-glibc.inc",
            "conf/distro/include/tcmode-default.inc",
            "conf/distro/include/uninative-flags.inc",
            "conf/distro/include/yocto-uninative.inc",
            "conf/machine/include/qemu.inc",
            "conf/machine/include/qemuboot-x86.inc",
            "conf/machine/include/tune-core2.inc",
            "conf/machine/include/tune-i586.inc",
            "conf/machine/include/tune-i686.inc",
            "conf/machine/include/x86/arch-x86.inc",
            "dynamic-distro/scatest/code-from-elsewhere/bad-po.bb"
        ],
        "BuildPath": "/mnt/data/yocto/build-sca-master/tmp/work/core2-64-scatest-linux/bad-po/1.0-r0/git/tests",
        "Line": "62",
        "Column": "1",
        "Severity": "warning",
        "Message": "whitespace at end: 0 in string, 1 in translation",
        "ID": "whitespace",
        "PackageName": "bad-po",
        "Tool": "msgcheck",
        "Scope": "style"
    },
    {
        "File": "fr_errors.po",
        "BBFiles": [
            "conf/distro/include/default-distrovars.inc",
            "conf/distro/include/default-providers.inc",
            "conf/distro/include/default-versions.inc",
            "conf/distro/include/init-manager-none.inc",
            "conf/distro/include/maintainers.inc",
            "conf/distro/include/no-static-libs.inc",
            "conf/distro/include/poky-world-exclude.inc",
            "conf/distro/include/security_flags.inc",
            "conf/distro/include/tclibc-glibc.inc",
            "conf/distro/include/tcmode-default.inc",
            "conf/distro/include/uninative-flags.inc",
            "conf/distro/include/yocto-uninative.inc",
            "conf/machine/include/qemu.inc",
            "conf/machine/include/qemuboot-x86.inc",
            "conf/machine/include/tune-core2.inc",
            "conf/machine/include/tune-i586.inc",
            "conf/machine/include/tune-i686.inc",
            "conf/machine/include/x86/arch-x86.inc",
            "dynamic-distro/scatest/code-from-elsewhere/bad-po.bb"
        ],
        "BuildPath": "/mnt/data/yocto/build-sca-master/tmp/work/core2-64-scatest-linux/bad-po/1.0-r0/git/tests",
        "Line": "65",
        "Column": "1",
        "Severity": "warning",
        "Message": "whitespace at beginning: 1 in string, 0 in translation",
        "ID": "whitespace",
        "PackageName": "bad-po",
        "Tool": "msgcheck",
        "Scope": "style"
    },
    {
        "File": "fr_errors.po",
        "BBFiles": [
            "conf/distro/include/default-distrovars.inc",
            "conf/distro/include/default-providers.inc",
            "conf/distro/include/default-versions.inc",
            "conf/distro/include/init-manager-none.inc",
            "conf/distro/include/maintainers.inc",
            "conf/distro/include/no-static-libs.inc",
            "conf/distro/include/poky-world-exclude.inc",
            "conf/distro/include/security_flags.inc",
            "conf/distro/include/tclibc-glibc.inc",
            "conf/distro/include/tcmode-default.inc",
            "conf/distro/include/uninative-flags.inc",
            "conf/distro/include/yocto-uninative.inc",
            "conf/machine/include/qemu.inc",
            "conf/machine/include/qemuboot-x86.inc",
            "conf/machine/include/tune-core2.inc",
            "conf/machine/include/tune-i586.inc",
            "conf/machine/include/tune-i686.inc",
            "conf/machine/include/x86/arch-x86.inc",
            "dynamic-distro/scatest/code-from-elsewhere/bad-po.bb"
        ],
        "BuildPath": "/mnt/data/yocto/build-sca-master/tmp/work/core2-64-scatest-linux/bad-po/1.0-r0/git/tests",
        "Line": "52",
        "Column": "1",
        "Severity": "warning",
        "Message": "end punctuation: \".\" in translation, \".\" not in string",
        "ID": "punct",
        "PackageName": "bad-po",
        "Tool": "msgcheck",
        "Scope": "style"
    },
    {
        "File": "fr_errors.po",
        "BBFiles": [
            "conf/distro/include/default-distrovars.inc",
            "conf/distro/include/default-providers.inc",
            "conf/distro/include/default-versions.inc",
            "conf/distro/include/init-manager-none.inc",
            "conf/distro/include/maintainers.inc",
            "conf/distro/include/no-static-libs.inc",
            "conf/distro/include/poky-world-exclude.inc",
            "conf/distro/include/security_flags.inc",
            "conf/distro/include/tclibc-glibc.inc",
            "conf/distro/include/tcmode-default.inc",
            "conf/distro/include/uninative-flags.inc",
            "conf/distro/include/yocto-uninative.inc",
            "conf/machine/include/qemu.inc",
            "conf/machine/include/qemuboot-x86.inc",
            "conf/machine/include/tune-core2.inc",
            "conf/machine/include/tune-i586.inc",
            "conf/machine/include/tune-i686.inc",
            "conf/machine/include/x86/arch-x86.inc",
            "dynamic-distro/scatest/code-from-elsewhere/bad-po.bb"
        ],
        "BuildPath": "/mnt/data/yocto/build-sca-master/tmp/work/core2-64-scatest-linux/bad-po/1.0-r0/git/tests",
        "Line": "71",
        "Column": "1",
        "Severity": "warning",
        "Message": "different whitespace at end of a line: 0 in string, 1 in translation",
        "ID": "whitespace_eol",
        "PackageName": "bad-po",
        "Tool": "msgcheck",
        "Scope": "style"
    },
    {
        "File": "fr_errors.po",
        "BBFiles": [
            "conf/distro/include/default-distrovars.inc",
            "conf/distro/include/default-providers.inc",
            "conf/distro/include/default-versions.inc",
            "conf/distro/include/init-manager-none.inc",
            "conf/distro/include/maintainers.inc",
            "conf/distro/include/no-static-libs.inc",
            "conf/distro/include/poky-world-exclude.inc",
            "conf/distro/include/security_flags.inc",
            "conf/distro/include/tclibc-glibc.inc",
            "conf/distro/include/tcmode-default.inc",
            "conf/distro/include/uninative-flags.inc",
            "conf/distro/include/yocto-uninative.inc",
            "conf/machine/include/qemu.inc",
            "conf/machine/include/qemuboot-x86.inc",
            "conf/machine/include/tune-core2.inc",
            "conf/machine/include/tune-i586.inc",
            "conf/machine/include/tune-i686.inc",
            "conf/machine/include/x86/arch-x86.inc",
            "dynamic-distro/scatest/code-from-elsewhere/bad-po.bb"
        ],
        "BuildPath": "/mnt/data/yocto/build-sca-master/tmp/work/core2-64-scatest-linux/bad-po/1.0-r0/git/tests",
        "Line": "59",
        "Column": "1",
        "Severity": "warning",
        "Message": "whitespace at end: 1 in string, 0 in translation",
        "ID": "whitespace",
        "PackageName": "bad-po",
        "Tool": "msgcheck",
        "Scope": "style"
    },
    {
        "File": "fr_errors.po",
        "BBFiles": [
            "conf/distro/include/default-distrovars.inc",
            "conf/distro/include/default-providers.inc",
            "conf/distro/include/default-versions.inc",
            "conf/distro/include/init-manager-none.inc",
            "conf/distro/include/maintainers.inc",
            "conf/distro/include/no-static-libs.inc",
            "conf/distro/include/poky-world-exclude.inc",
            "conf/distro/include/security_flags.inc",
            "conf/distro/include/tclibc-glibc.inc",
            "conf/distro/include/tcmode-default.inc",
            "conf/distro/include/uninative-flags.inc",
            "conf/distro/include/yocto-uninative.inc",
            "conf/machine/include/qemu.inc",
            "conf/machine/include/qemuboot-x86.inc",
            "conf/machine/include/tune-core2.inc",
            "conf/machine/include/tune-i586.inc",
            "conf/machine/include/tune-i686.inc",
            "conf/machine/include/x86/arch-x86.inc",
            "dynamic-distro/scatest/code-from-elsewhere/bad-po.bb"
        ],
        "BuildPath": "/mnt/data/yocto/build-sca-master/tmp/work/core2-64-scatest-linux/bad-po/1.0-r0/git/tests",
        "Line": "74",
        "Column": "1",
        "Severity": "warning",
        "Message": "different whitespace at end of a line: 1 in string, 0 in translation",
        "ID": "whitespace_eol",
        "PackageName": "bad-po",
        "Tool": "msgcheck",
        "Scope": "style"
    },
    {
        "File": "fr_errors.po",
        "BBFiles": [
            "conf/distro/include/default-distrovars.inc",
            "conf/distro/include/default-providers.inc",
            "conf/distro/include/default-versions.inc",
            "conf/distro/include/init-manager-none.inc",
            "conf/distro/include/maintainers.inc",
            "conf/distro/include/no-static-libs.inc",
            "conf/distro/include/poky-world-exclude.inc",
            "conf/distro/include/security_flags.inc",
            "conf/distro/include/tclibc-glibc.inc",
            "conf/distro/include/tcmode-default.inc",
            "conf/distro/include/uninative-flags.inc",
            "conf/distro/include/yocto-uninative.inc",
            "conf/machine/include/qemu.inc",
            "conf/machine/include/qemuboot-x86.inc",
            "conf/machine/include/tune-core2.inc",
            "conf/machine/include/tune-i586.inc",
            "conf/machine/include/tune-i686.inc",
            "conf/machine/include/x86/arch-x86.inc",
            "dynamic-distro/scatest/code-from-elsewhere/bad-po.bb"
        ],
        "BuildPath": "/mnt/data/yocto/build-sca-master/tmp/work/core2-64-scatest-linux/bad-po/1.0-r0/git/tests",
        "Line": "68",
        "Column": "1",
        "Severity": "warning",
        "Message": "whitespace at beginning: 0 in string, 1 in translation",
        "ID": "whitespace",
        "PackageName": "bad-po",
        "Tool": "msgcheck",
        "Scope": "style"
    },
    {
        "File": "fr_errors.po",
        "BBFiles": [
            "conf/distro/include/default-distrovars.inc",
            "conf/distro/include/default-providers.inc",
            "conf/distro/include/default-versions.inc",
            "conf/distro/include/init-manager-none.inc",
            "conf/distro/include/maintainers.inc",
            "conf/distro/include/no-static-libs.inc",
            "conf/distro/include/poky-world-exclude.inc",
            "conf/distro/include/security_flags.inc",
            "conf/distro/include/tclibc-glibc.inc",
            "conf/distro/include/tcmode-default.inc",
            "conf/distro/include/uninative-flags.inc",
            "conf/distro/include/yocto-uninative.inc",
            "conf/machine/include/qemu.inc",
            "conf/machine/include/qemuboot-x86.inc",
            "conf/machine/include/tune-core2.inc",
            "conf/machine/include/tune-i586.inc",
            "conf/machine/include/tune-i686.inc",
            "conf/machine/include/x86/arch-x86.inc",
            "dynamic-distro/scatest/code-from-elsewhere/bad-po.bb"
        ],
        "BuildPath": "/mnt/data/yocto/build-sca-master/tmp/work/core2-64-scatest-linux/bad-po/1.0-r0/git/tests",
        "Line": "48",
        "Column": "1",
        "Severity": "warning",
        "Message": "end punctuation: \".\" in string, \".\" not in translation",
        "ID": "punct",
        "PackageName": "bad-po",
        "Tool": "msgcheck",
        "Scope": "style"
    }
]